[project]
name = "tenant-first-aid"
version = "0.2.0"
requires-python = ">=3.12"
dependencies = [
  "flask",
  "valkey",
  "gunicorn",
  "openai",
  "jsonlines",
  "simplejson",
  "ipdb>=0.13.13",
  "python-dotenv",
  "pandas",
  "pandarallel",
  ]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["data*"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "ruff>=0.11.13",
    "ty>=0.0.1a8",
    "types-Flask>=1.1.6",
]

gen_convo = [
      "pandas",
      "openai",
]

